base_config: ../default.yaml
target_construction:
  fire_mask:
    method: threshold_union
    energy_threshold_mw: 0.0073115709237754345
    surface_fuel_threshold: 4.000000444648322e-06
    canopy_fuel_threshold: 0.007817625999450684
    threshold_file: /scratch/mhabibp/cawfe_datasets/cawfe_engineered_v1/thresholds/fire_mask_thresholds_latest.json
    require_frozen_thresholds: true
